import '@/app/global.css'
import '@radix-ui/themes/styles.css'
import type { Metadata } from 'next'
import { Theme } from '@radix-ui/themes'
import { CustomErrorBoudary } from '@/suspense/error/error-boundary'
import DefaultLayout from '@/components/DefaultLayout/DefaultLayout'

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <Theme
          accentColor='gray'
          appearance='dark'
          grayColor='sand'
          radius='large'
          scaling='95%'
        >
          <DefaultLayout>
            <CustomErrorBoudary>
              {children}
            </CustomErrorBoudary>
          </DefaultLayout>
        </Theme>
      </body>
    </html>
  )
}
